ALTER TABLE categories MODIFY name VARCHAR(50) UNIQUE;
ALTER TABLE products MODIFY price DECIMAL(16,2);
ALTER TABLE products MODIFY thumbnail VARCHAR(255);

ALTER TABLE users MODIFY COLUMN phone_number VARCHAR(11);
ALTER TABLE users ALTER COLUMN role_id SET DEFAULT 2;

